
mytheme2 <- theme(axis.text.x = element_text(angle = 88, hjust=0, vjust=0.5, size = 13, color = "black", face = "plain"),
                  axis.text.y = element_text(hjust=0, vjust=0, size = 14, color = "black", face = "plain"),
                  axis.ticks = element_blank(),
                  axis.title = element_blank(),
                  panel.background =  element_blank(),
                  panel.border = element_blank(),
                  strip.background =element_blank(),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.grid.major.y = element_line(colour="gray80", size=0.1),
                  panel.spacing.x = unit(0.8, "lines"),
                  panel.spacing.y = unit(-0.05, "lines"),
                  plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm"),
                  strip.text.x = element_text(hjust=0, vjust=-1, size = 13, color = "black", face = "bold"),
                  legend.position="right",
                  legend.background = element_rect(fill = "white"),
                  legend.key = element_rect(fill = "white", color = NA),
                  legend.title = element_blank()) 
